SET FOREIGN_KEY_CHECKS=0;
INSERT INTO `companies` (`id`, `name`, `business_name`, `cuit`, `email`, `location`, `user_status_id`, `created_at`, `updated_at`) VALUES
INSERT INTO `company_roles` (`id`, `company_id`, `job_role`, `created_at`, `updated_at`) VALUES
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
INSERT INTO `parks` (`id`, `park_name`, `district`, `latitude`, `longitude`, `created_at`, `updated_at`) VALUES
INSERT INTO `planters` (`id`, `street_id`, `planter_state`, `position`, `height`, `street_width`, `created_at`, `updated_at`) VALUES
INSERT INTO `priorities` (`id`, `priority_name`, `slug`, `created_at`, `updated_at`) VALUES
INSERT INTO `requests` (`id`, `user_id`, `tree_id`, `request_type_id`, `street_id`, `description`, `path`, `request_status_id`, `is_new_for_user`, `cancellation_reason`, `priority_id`, `linked_to`, `suggested_duplicate_id`, `risk_score`, `urgente_sla`, `created_at`, `updated_at`) VALUES
INSERT INTO `request_statuses` (`id`, `status_name`, `slug`, `sequence`, `is_terminal`, `color`, `created_at`, `updated_at`) VALUES
INSERT INTO `request_status_histories` (`id`, `request_id`, `request_status_id`, `user_id`, `justification`, `created_at`, `updated_at`) VALUES
INSERT INTO `request_types` (`id`, `task_description`, `created_at`, `updated_at`) VALUES
INSERT INTO `species` (`id`, `scientific_name`, `common_name`, `family`, `origin`, `foliage_type`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `streets` (`id`, `street_name`, `street_number`, `door_plate`, `district`, `created_at`, `updated_at`) VALUES
INSERT INTO `trees` (`id`, `species_id`, `planter_id`, `street_id`, `reference`, `park_id`, `latitude`, `longitude`, `years`, `height`, `dap`, `maintenance_status`, `vitality`, `structure`, `degree`, `observations`, `created_at`, `updated_at`) VALUES
INSERT INTO `trees` (`id`, `species_id`, `planter_id`, `street_id`, `reference`, `park_id`, `latitude`, `longitude`, `years`, `height`, `dap`, `maintenance_status`, `vitality`, `structure`, `degree`, `observations`, `created_at`, `updated_at`) VALUES
INSERT INTO `trees` (`id`, `species_id`, `planter_id`, `street_id`, `reference`, `park_id`, `latitude`, `longitude`, `years`, `height`, `dap`, `maintenance_status`, `vitality`, `structure`, `degree`, `observations`, `created_at`, `updated_at`) VALUES
INSERT INTO `trees` (`id`, `species_id`, `planter_id`, `street_id`, `reference`, `park_id`, `latitude`, `longitude`, `years`, `height`, `dap`, `maintenance_status`, `vitality`, `structure`, `degree`, `observations`, `created_at`, `updated_at`) VALUES
INSERT INTO `trees` (`id`, `species_id`, `planter_id`, `street_id`, `reference`, `park_id`, `latitude`, `longitude`, `years`, `height`, `dap`, `maintenance_status`, `vitality`, `structure`, `degree`, `observations`, `created_at`, `updated_at`) VALUES
INSERT INTO `users` (`id`, `name`, `last_name`, `email`, `email_verified_at`, `password`, `role`, `company_id`, `user_status_id`, `profile_photo`, `remember_token`, `created_at`, `updated_at`) VALUES
INSERT INTO `user_statuses` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
INSERT INTO `work_orders` (`id`, `request_id`, `company_id`, `task_description`, `scheduled_date`, `execution_order`, `work_status`, `payment_status`, `cost`, `created_at`, `updated_at`) VALUES
SET FOREIGN_KEY_CHECKS=1;
